name: Node.js Deployment with NGINX and SSL

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |


            # Fetch latest changes and reset to main branch
            git fetch --all
            git reset --hard origin/main

            # Setup environment and dependencies
            cp .env.example .env

            npm install --legacy-peer-deps
            npm run build

            # Manage PM2 process
            if pm2 list | grep -q "zrf-client"; then
              echo "PM2 process already exists. Restarting..."
              pm2 restart zrf-client
            else
              echo "No PM2 process found. Starting..."
              pm2 start npm --name "zrf-client" -- start
            fi

            # Save PM2 process list
            pm2 save
